// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.37.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// The functions `parse_response`, `send_request`, `send_get_request`, `send_post_request`, `send_put_request`, `send_delete_request` are not `pub`, thus are ignored.

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<APIClient>>
@sealed
class ApiClient extends RustOpaque {
  // Not to be used by end users
  ApiClient.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ApiClient.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_ApiClient,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_ApiClient,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_ApiClientPtr,
  );

  Future<String> getBaseUrl() =>
      RustLib.instance.api.crateApiClientApiClientGetBaseUrl(
        that: this,
      );

  Future<String?> getCookies() =>
      RustLib.instance.api.crateApiClientApiClientGetCookies(
        that: this,
      );

  Future<Response> loginUser(
          {required String email, required String password}) =>
      RustLib.instance.api.crateApiClientApiClientLoginUser(
          that: this, email: email, password: password);

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<ApiClient> newInstance({required String baseUrl}) =>
      RustLib.instance.api.crateApiClientApiClientNew(baseUrl: baseUrl);

  Future<Response> processImage({required String imagePath}) => RustLib
      .instance.api
      .crateApiClientApiClientProcessImage(that: this, imagePath: imagePath);

  Future<Response> registerUser(
          {required String name,
          required String email,
          required String password}) =>
      RustLib.instance.api.crateApiClientApiClientRegisterUser(
          that: this, name: name, email: email, password: password);
}

class Response {
  final int statusCode;
  final String body;

  const Response({
    required this.statusCode,
    required this.body,
  });

  @override
  int get hashCode => statusCode.hashCode ^ body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Response &&
          runtimeType == other.runtimeType &&
          statusCode == other.statusCode &&
          body == other.body;
}
